from pathlib import Path

OUTPUT_DIR = Path("Races")
INPUT_DIR  = Path("input_folder")
# INPUT_DIR = Path("diag_input_folder")
DIAGNOSTIC_OUTPUT_DIR = Path("diag/.")
FILE_NAMES_LIST_OUTPUT_DIR = Path("links/.")
FILE_NAMES_LIST            = FILE_NAMES_LIST_OUTPUT_DIR / Path("file_names.md")

LEVEL_1_HEADER = "# "
LEVEL_2_HEADER = "## "
LEVEL_3_HEADER = "### "
LEVEL_4_HEADER = "#### "
LEVEL_5_HEADER = "##### "
BOLD_HEADER    = "***"
HEADER_PREFIXES = (LEVEL_1_HEADER, LEVEL_2_HEADER, LEVEL_3_HEADER, LEVEL_4_HEADER, LEVEL_5_HEADER,)

PATTERN_LIST = [
    "Blinded",
    "Charmed",
    "Deafened",
    "Exhaustion",
    "Frightened",
    "Grappled",
    "Incapacitated",
    "Invisible",
    "Paralyzed",
    "Petrified",
    "Poisoned",
    "Prone",
    "Restrained",
    "Stunned",
    "Unconscious",
    "Spells Alphabetical",
    "Artificer Spells",
    "Bard Spells",
    "Cleric Spells",
    "Druid Spells",
    "Paladin Spells",
    "Ranger Spells",
    "Sorcerer Spells",
    "Warlock Spells",
    "Wizard Spells",
    "Artificer",
    "Bard",
    "Cleric",
    "Druid",
    "Paladin",
    "Ranger",
    "Sorcerer",
    "Warlock",
    "Wizard",
    "Spells",
    "Abi-Dalzim's Horrid Wilting",
    "Absorb Elements",
    "Acid Splash",
    "Aganazzar's Scorcher",
    "Aid",
    "Air Bubble",
    "Alarm",
    "Alter Self",
    "Alustriel's Mooncloak",
    "Animal Friendship",
    "Animal Messenger",
    "Animal Shapes",
    "Animate Dead",
    "Animate Objects",
    "Antagonize",
    "Antilife Shell",
    "Antimagic Field",
    "AntipathySympathy",
    "Arcane Eye",
    "Arcane Gate",
    "Arcane Lock",
    "Arcane Vigor",
    "Armor of Agathys",
    "Arms of Hadar",
    "Ashardalon's Stride",
    "Astral Projection",
    "Augury",
    "Aura of Life",
    "Aura of Purity",
    "Aura of Vitality",
    "Awaken",
    "Backlash",
    "Bane",
    "Banishing Smite",
    "Banishment",
    "Barkskin",
    "Beacon of Hope",
    "Beast Bond",
    "Beast Sense",
    "Befuddlement",
    "Bestow Curse",
    "Bigby's Hand",
    "Blade Barrier",
    "Blade of Disaster",
    "Blade Ward",
    "Bless",
    "Blight",
    "Blinding Smite",
    "BlindnessDeafness",
    "Blink",
    "Blur",
    "Bones of the Earth",
    "Booming Blade",
    "Burning Hands",
    "Cacophonic Shield",
    "Call Lightning",
    "Calm Emotions",
    "Catapult",
    "Catnap",
    "Cause Fear",
    "Ceremony",
    "Chain Lightning",
    "Chaos Bolt",
    "Charm Monster",
    "Charm Person",
    "Chill Touch",
    "Chromatic Orb",
    "Circle of Death",
    "Circle of Power",
    "Clairvoyance",
    "Clone",
    "Cloud of Daggers",
    "Cloudkill",
    "Color Spray",
    "Command",
    "Commune",
    "Commune with Nature",
    "Compelled Duel",
    "Comprehend Languages",
    "Compulsion",
    "Cone of Cold",
    "Confusion",
    "Conjure Animals",
    "Conjure Barrage",
    "Conjure Celestial",
    "Conjure Constructs",
    "Conjure Elemental",
    "Conjure Fey",
    "Conjure Minor Elementals",
    "Conjure Volley",
    "Conjure Woodland Beings",
    "Contact Other Plane",
    "Contagion",
    "Contingency",
    "Continual Flame",
    "Control Flames",
    "Control Water",
    "Control Weather",
    "Control Winds",
    "Cordon of Arrows",
    "Counterspell",
    "Create Bonfire",
    "Create Food and Water",
    "Create Homunculus",
    "Create or Destroy Water",
    "Create Spelljamming Helm",
    "Create Undead",
    "Creation",
    "Crown of Madness",
    "Crown of Stars",
    "Crusader's Mantle",
    "Cure Wounds",
    "Dancing Lights",
    "Danse Macabre",
    "Dark Star",
    "Darkness",
    "Darkvision",
    "Dawn",
    "Daylight",
    "Death Armor",
    "Death Ward",
    "Delayed Blast Fireball",
    "Demiplane",
    "Deryan's Helpful Homunculi",
    "Destructive Wave",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "Detect Thoughts",
    "Dimension Door",
    "Dirge",
    "Disguise Self",
    "Disintegrate",
    "Dispel Evil and Good",
    "Dispel Magic",
    "Dissonant Whispers",
    "Distort Value",
    "Divination",
    "Divine Favor",
    "Divine Smite",
    "Divine Word",
    "Dominate Beast",
    "Dominate Monster",
    "Dominate Person",
    "Doomtide",
    "Draconic Transformation",
    "Dragon's Breath",
    "Drawmij's Instant Summons",
    "Dream",
    "Dream of the Blue Veil",
    "Druid Grove",
    "Druidcraft",
    "Dust Devil",
    "Earth Tremor",
    "Earthbind",
    "Earthquake",
    "Eldritch Blast",
    "Elemental Bane",
    "Elemental Weapon",
    "Elementalism",
    "Elminster's Effulgent Spheres",
    "Elminster's Elusion",
    "Encode Thoughts",
    "Enemies Abound",
    "Enervation",
    "Enhance Ability",
    "EnlargeReduce",
    "Ensnaring Strike",
    "Entangle",
    "Enthrall",
    "Erupting Earth",
    "Etherealness",
    "Evard's Black Tentacles",
    "Expeditious Retreat",
    "Eyebite",
    "Fabricate",
    "Faerie Fire",
    "False Life",
    "Far Step",
    "Fast Friends",
    "Fear",
    "Feather Fall",
    "Feign Death",
    "Find Familiar",
    "Find Greater Steed",
    "Find Steed",
    "Find the Path",
    "Find Traps",
    "Finger of Death",
    "Fire Bolt",
    "Fire Shield",
    "Fire Storm",
    "Fireball",
    "Fizban's Platinum Shield",
    "Flame Arrows",
    "Flame Blade",
    "Flame Strike",
    "Flaming Sphere",
    "Flesh to Stone",
    "Fly",
    "Fog Cloud",
    "Forbiddance",
    "Forcecage",
    "Foresight",
    "Fortune's Favor",
    "Fount of Moonlight",
    "Freedom of Movement",
    "Friends",
    "Frostbite",
    "Gaseous Form",
    "Gate",
    "Gate Seal",
    "Geas",
    "Gentle Repose",
    "Giant Insect",
    "Gift of Alacrity",
    "Gift of Gab",
    "Glibness",
    "Globe of Invulnerability",
    "Glyph of Warding",
    "Goodberry",
    "Grasping Vine",
    "Gravity Fissure",
    "Gravity Sinkhole",
    "Grease",
    "Greater Invisibility",
    "Greater Restoration",
    "Green-Flame Blade",
    "Guardian of Faith",
    "Guardian of Nature",
    "Guards and Wards",
    "Guidance",
    "Guiding Bolt",
    "Gust",
    "Gust of Wind",
    "Hail of Thorns",
    "Hallow",
    "Hallucinatory Terrain",
    "Harm",
    "Haste",
    "Heal",
    "Healing Spirit",
    "Healing Word",
    "Heat Metal",
    "Hellish Rebuke",
    "Heroes' Feast",
    "Heroism",
    "Hex",
    "Hold Monster",
    "Hold Person",
    "Holy Aura",
    "Holy Star of Mystra",
    "Holy Weapon",
    "Homunculus Servant",
    "Hunger of Hadar",
    "Hunter's Mark",
    "Hypnotic Pattern",
    "Ice Knife",
    "Ice Storm",
    "Identify",
    "Illusory Dragon",
    "Illusory Script",
    "Immolation",
    "Immovable Object",
    "Imprisonment",
    "Incendiary Cloud",
    "Incite Greed",
    "Infernal Calling",
    "Infestation",
    "Inflict Wounds",
    "Insect Plague",
    "Intellect Fortress",
    "Investiture of Flame",
    "Investiture of Ice",
    "Investiture of Stone",
    "Investiture of Wind",
    "Invisibility",
    "Invulnerability",
    "Jallarzi's Storm of Radiance",
    "Jim's Glowing Coin",
    "Jim's Magic Missile",
    "Jump",
    "Knock",
    "Laeral's Silver Lance",
    "Legend Lore",
    "Leomund's Secret Chest",
    "Leomund's Tiny Hut",
    "Lesser Restoration",
    "Levitate",
    "Life Transference",
    "Light (Spell)",
    "Lightning Arrow",
    "Lightning Bolt",
    "Lightning Lure",
    "Locate Animals or Plants",
    "Locate Creature",
    "Locate Object",
    "Longstrider",
    "Maddening Darkness",
    "Maelstrom",
    "Mage Armor",
    "Mage Hand",
    "Magic Circle",
    "Magic Jar",
    "Magic Missile",
    "Magic Mouth",
    "Magic Stone",
    "Magic Weapon",
    "Magnify Gravity",
    "Major Image",
    "Mass Cure Wounds",
    "Mass Heal",
    "Mass Healing Word",
    "Mass Polymorph",
    "Mass Suggestion",
    "Maximilian's Earthen Grasp",
    "Maze",
    "Meld into Stone",
    "Melf's Acid Arrow",
    "Melf's Minute Meteors",
    "Mending",
    "Mental Prison",
    "Message",
    "Meteor Swarm",
    "Mighty Fortress",
    "Mind Blank",
    "Mind Sliver",
    "Mind Spike",
    "Minor Illusion",
    "Mirage Arcane",
    "Mirror Image",
    "Mislead",
    "Misty Step",
    "Modify Memory",
    "Mold Earth",
    "Moonbeam",
    "Mordenkainen's Faithful Hound",
    "Mordenkainen's Magnificent Mansion",
    "Mordenkainen's Private Sanctum",
    "Mordenkainen's Sword",
    "Motivational Speech",
    "Move Earth",
    "Nathair's Mischief",
    "Negative Energy Flood",
    "Nondetection",
    "Nystul's Magic Aura",
    "Otiluke's Freezing Sphere",
    "Otiluke's Resilient Sphere",
    "Otto's Irresistible Dance",
    "Pass without Trace",
    "Passwall",
    "Phantasmal Force",
    "Phantasmal Killer",
    "Phantom Steed",
    "Planar Ally",
    "Planar Binding",
    "Plane Shift",
    "Plant Growth",
    "Poison Spray",
    "Polymorph",
    "Power Word Fortify",
    "Power Word Heal",
    "Power Word Kill",
    "Power Word Pain",
    "Power Word Stun",
    "Prayer of Healing",
    "Prestidigitation",
    "Primal Savagery",
    "Primordial Ward",
    "Prismatic Spray",
    "Prismatic Wall",
    "Produce Flame",
    "Programmed Illusion",
    "Project Image",
    "Protection from Energy",
    "Protection from Evil and Good",
    "Protection from Poison",
    "Psychic Scream",
    "Pulse Wave",
    "Purify Food and Drink",
    "Pyrotechnics",
    "Raise Dead",
    "Rary's Telepathic Bond",
    "Raulothim's Psychic Lance",
    "Ravenous Void",
    "Ray of Enfeeblement",
    "Ray of Frost",
    "Ray of Sickness",
    "Reality Break",
    "Regenerate",
    "Reincarnate",
    "Remove Curse",
    "Resistance",
    "Resurrection",
    "Reverse Gravity",
    "Revivify",
    "Rime's Binding Ice",
    "Rope Trick",
    "Sacred Flame",
    "Sanctuary",
    "Sapping Sting",
    "Scatter",
    "Scorching Ray",
    "Scrying",
    "Searing Smite",
    "See Invisibility",
    "Seeming",
    "Sending",
    "Sequester",
    "Shadow Blade",
    "Shadow of Moil",
    "Shape Water",
    "Shapechange",
    "Shatter",
    "Shield",
    "Shield of Faith",
    "Shillelagh",
    "Shining Smite",
    "Shocking Grasp",
    "Sickening Radiance",
    "Silence",
    "Silent Image",
    "Simbul's Synostodweomer",
    "Simulacrum",
    "Skill Empowerment",
    "Skywrite",
    "Sleep",
    "Sleet Storm",
    "Slow (Spell)",
    "Snare",
    "Snilloc's Snowball Swarm",
    "Songal's Elemental Suffusion",
    "Sorcerous Burst",
    "Soul Cage",
    "Spare the Dying",
    "Speak with Animals",
    "Speak with Dead",
    "Speak with Plants",
    "Spellfire Flare",
    "Spellfire Storm",
    "Spider Climb",
    "Spike Growth",
    "Spirit Guardians",
    "Spirit of Death",
    "Spirit Shroud",
    "Spiritual Weapon",
    "Spray of Cards",
    "Staggering Smite",
    "Starry Wisp",
    "Steel Wind Strike",
    "Stinking Cloud",
    "Stone Shape",
    "Stoneskin",
    "Storm of Vengeance",
    "Storm Sphere",
    "Suggestion",
    "Summon Aberration",
    "Summon Beast",
    "Summon Celestial",
    "Summon Construct",
    "Summon Draconic Spirit",
    "Summon Dragon",
    "Summon Elemental",
    "Summon Fey",
    "Summon Fiend",
    "Summon Greater Demon",
    "Summon Lesser Demons",
    "Summon Shadowspawn",
    "Summon Undead",
    "Sunbeam",
    "Sunburst",
    "Swift Quiver",
    "Sword Burst",
    "Syluné's Viper",
    "Symbol",
    "Synaptic Static",
    "Tasha's Bubbling Cauldron",
    "Tasha's Caustic Brew",
    "Tasha's Hideous Laughter",
    "Tasha's Mind Whip",
    "Tasha's Otherworldly Guise",
    "Telekinesis",
    "Telepathy",
    "Teleport",
    "Teleportation Circle",
    "Temple of the Gods",
    "Temporal Shunt",
    "Tenser's Floating Disk",
    "Tenser's Transformation",
    "Tether Essence",
    "Thaumaturgy",
    "Thorn Whip",
    "Thunder Step",
    "Thunderclap",
    "Thunderous Smite",
    "Thunderwave",
    "Tidal Wave",
    "Time Ravage",
    "Time Stop",
    "Tiny Servant",
    "Toll the Dead",
    "Tongues",
    "Transmute Rock",
    "Transport via Plants",
    "Tree Stride",
    "True Polymorph",
    "True Resurrection",
    "True Seeing",
    "True Strike",
    "Tsunami",
    "Unseen Servant",
    "Vampiric Touch",
    "Vicious Mockery",
    "Vitriolic Sphere",
    "Wall of Fire",
    "Wall of Force",
    "Wall of Ice",
    "Wall of Light",
    "Wall of Sand",
    "Wall of Stone",
    "Wall of Thorns",
    "Wall of Water",
    "Wardaway",
    "Warding Bond",
    "Warding Wind",
    "Warp Sense",
    "Water Breathing",
    "Water Walk",
    "Watery Sphere",
    "Web",
    "Weird",
    "Whirlwind",
    "Wind Walk",
    "Wind Wall",
    "Wish",
    "Witch Bolt",
    "Word of Radiance",
    "Word of Recall",
    "Wrath of Nature",
    "Wrathful Smite",
    "Wristpocket",
    "Yolande's Regal Presence",
    "Zephyr Strike",
    "Zone of Truth",
    "Spells Alphabetical",
    "Artificer Spells",
    "Bard Spells",
    "Cleric Spells",
    "Druid Spells",
    "Paladin Spells",
    "Ranger Spells",
    "Sorcerer Spells",
    "Warlock Spells",
    "Wizard Spells",
]

